

const asks=['Onde está a saída?','Esta cama cabe no meu Fiat Punto?','Tem isto em amarelo, mas mais azul?','Posso levar o quarto inteiro no carrinho?','Este roupeiro vem já montado?','As almofadas têm manual?'];
const quotes=['Está tratado!','Isto não vinha no manual.','Mais uma cama, menos um problema.','Quem deixou este roupeiro aqui?','Eu só queria acabar o turno.'];
const powers=['Café de Máquina','Chave Allen Lendária','Modo Sorriso Profissional','Pausa de 5 Minutos','Crachá Dourado'];
function clamp(v,a,b){return Math.max(a,Math.min(b,v))} function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
const {useEffect,useRef,useState}=React;
const luisPhoto=new Image(); luisPhoto.src='/luis.jpg';
function App(){const canvas=useRef(null);const keys=useRef({});const pointer=useRef(null);const [screen,setScreen]=useState('menu');const [score,setScore]=useState(0);const [chaos,setChaos]=useState(10);const [time,setTime]=useState(300);const [toast,setToast]=useState('');const [mini,setMini]=useState(null);const game=useRef({l:{x:420,y:310},items:[],customers:[],tick:0,freeze:0,speed:0,allen:0,smile:0,photo:0});
 const reset=()=>{game.current={l:{x:420,y:310},items:spawnItems(),customers:spawnCustomers(),tick:0,freeze:0,speed:0,allen:0,smile:0,photo:0};setScore(0);setChaos(8);setTime(300);setToast('Faltam 5 minutos para abrir a MÓVEA!');setMini(null);setScreen('play')};
 useEffect(()=>{const d=(e)=>{keys.current[e.key.toLowerCase()]=true;if(e.key===' ') e.preventDefault()}; const u=(e)=>{keys.current[e.key.toLowerCase()]=false}; addEventListener('keydown',d);addEventListener('keyup',u);return()=>{removeEventListener('keydown',d);removeEventListener('keyup',u)}},[]);
 useEffect(()=>{let raf=0,last=performance.now(); const loop=(now)=>{const dt=Math.min(.033,(now-last)/1000);last=now;if(screen==='play') update(dt); draw(); raf=requestAnimationFrame(loop)}; raf=requestAnimationFrame(loop);return()=>cancelAnimationFrame(raf)},[screen,mini,score,chaos,time]);
 function update(dt){const g=game.current; g.tick+=dt; if(g.freeze>0)g.freeze-=dt;if(g.speed>0)g.speed-=dt;if(g.allen>0)g.allen-=dt;if(g.smile>0)g.smile-=dt;if(g.photo>0)g.photo-=dt; setTime(t=>{const n=t-dt;if(n<=0){setScreen('over');return 0}return n}); let vx=(keys.current.d||keys.current.arrowright?1:0)-(keys.current.a||keys.current.arrowleft?1:0), vy=(keys.current.s||keys.current.arrowdown?1:0)-(keys.current.w||keys.current.arrowup?1:0); if(pointer.current){vx=pointer.current.x-g.l.x;vy=pointer.current.y-g.l.y;if(Math.hypot(vx,vy)<18){vx=0;vy=0}} const m=Math.hypot(vx,vy)||1; g.l.x=clamp(g.l.x+vx/m*(g.speed>0?260:150)*dt,35,965);g.l.y=clamp(g.l.y+vy/m*(g.speed>0?260:150)*dt,70,620);
  if(g.tick>8){g.tick=0;g.customers.push({id:Date.now(),x:920,y:80+Math.random()*480,patience:100,ask:asks[Math.floor(Math.random()*asks.length)]}); if(Math.random()<.7) g.items.push(makeItem(Date.now()))}
  g.customers.forEach(c=>{if(g.freeze<=0){c.patience-=dt*(g.smile>0?1.5:6+chaos/10); c.x+=Math.sin(Date.now()/700+c.id)*8*dt} if(c.happy)c.happy-=dt}); g.customers=g.customers.filter(c=>c.patience>0&&(!c.happy||c.happy>0)); const angry=g.customers.filter(c=>c.patience<30).length; setChaos(ch=>clamp(ch+angry*dt*.9+(g.customers.length>5?dt*2:0)-dt*1.6,0,100)); if(chaos>=99)setScreen('over');
  const interact=keys.current[' ']||keys.current.e; if(interact){ for(const it of g.items){if(!it.done&&dist(g.l,it)<48){handleItem(it);break}} for(const c of g.customers){if(!c.happy&&dist(g.l,c)<58){c.happy=1.2; setScore(s=>s+75); say('Cliente convencido: “Perfeito, era quase isto!”'); setChaos(ch=>clamp(ch-8,0,100));break}} }
  if(mini){setMini(mm=>mm?{...mm,t:mm.t-dt}:null); if(keys.current[' ']&&mini.t>0){setMini(mm=>mm?{...mm,hit:mm.hit+1}:null); keys.current[' ']=false} if(mini.t<=0){ if(mini.hit>=mini.need){setScore(s=>s+350);say('Cama montada com estilo olímpico!')} else setChaos(ch=>clamp(ch+18,0,100)); setMini(null)}} }
 function handleItem(it){const g=game.current; it.done=true; if(it.type==='power'&&it.power){if(it.power==='Café de Máquina')g.speed=7;if(it.power==='Chave Allen Lendária')g.allen=8;if(it.power==='Modo Sorriso Profissional')g.smile=8;if(it.power==='Pausa de 5 Minutos')g.freeze=5;if(it.power==='Crachá Dourado')g.photo=4; setScore(s=>s+200);say('POWER-UP: '+it.power+'!');return} if(it.type==='bed'&&g.allen<=0){setMini({t:5,need:9,hit:0});say('MINIJOGO: carrega ESPAÇO para montar a cama!')} else {setScore(s=>s+120);setChaos(ch=>clamp(ch-5,0,100));say(quotes[Math.floor(Math.random()*quotes.length)])}}
 function say(s){setToast(s);setTimeout(()=>setToast(''),1800)}
 function draw(){const c=canvas.current;if(!c)return; const ctx=c.getContext('2d'), w=c.width=1000,h=c.height=650; ctx.clearRect(0,0,w,h); drawStore(ctx,w,h); const g=game.current; g.items.filter(i=>!i.done).forEach(i=>drawItem(ctx,i)); g.customers.forEach(cu=>drawCustomer(ctx,cu)); drawLuis(ctx,g.l,g.photo>0); if(screen!=='play') drawMenu(ctx,w,h,screen); if(mini) drawMini(ctx,mini); }
 return <><canvas ref={canvas} onPointerDown={e=>{const r=e.currentTarget.getBoundingClientRect();pointer.current={x:(e.clientX-r.left)/r.width*1000,y:(e.clientY-r.top)/r.height*650}}} onPointerMove={e=>{if(e.buttons){const r=e.currentTarget.getBoundingClientRect();pointer.current={x:(e.clientX-r.left)/r.width*1000,y:(e.clientY-r.top)/r.height*650}}} onPointerUp={()=>pointer.current=null}/><div className="hud"><b>LUÍS: O REI DOS QUARTOS</b><span>Pontos {score}</span><span>Tempo {Math.ceil(time)}s</span><span className="bar"><i style={{width:chaos+'%'}}/></span></div>{toast&&<div className="toast">{toast}</div>}<div className="controls">WASD/Setas · Espaço/E ajuda/organiza · Telemóvel: arrasta no ecrã</div>{screen==='menu'&&<div className="panel"><h1>LUÍS: O REI DOS QUARTOS</h1><p>O departamento abre em 5 minutos. As almofadas já sabem.</p><button onClick={reset}>COMEÇAR O TURNO</button><button onClick={()=>setScreen('inst')}>INSTRUÇÕES</button><ol><li>Zé das Almofadas</li><li>Marta do Roupeiro</li><li>Cliente Sem Medidas</li><li>Luís Supremo</li></ol></div>}{screen==='inst'&&<div className="panel"><h2>Instruções</h2><p>Move o Luís, aproxima-te de objetos/clientes e carrega Espaço. Baixa o caos, ganha power-ups e sobrevive ao turno.</p><button onClick={()=>setScreen('menu')}>VOLTAR</button></div>}{screen==='over'&&<div className="panel"><h1>Fim do turno</h1><p>O departamento venceu. Luís tentou, mas as almofadas eram demasiadas.</p><h2>{score} pontos</h2><button onClick={reset}>TENTAR OUTRA VEZ</button></div>}</>}
}
function spawnItems(){return Array.from({length:18},(_,i)=>makeItem(i))} function makeItem(id){const r=Math.random(), type=r<.25?'bed':r<.5?'pillow':r<.72?'tag':r<.9?'wardrobe':'power'; return {id,type:type,x:70+Math.random()*850,y:100+Math.random()*480,power:type==='power'?powers[Math.floor(Math.random()*powers.length)]:undefined}} function spawnCustomers(){return Array.from({length:5},(_,i)=>({id:i,x:120+Math.random()*760,y:120+Math.random()*430,patience:70+Math.random()*30,ask:asks[i]}))}
function drawStore(ctx,w,h){const grd=ctx.createLinearGradient(0,0,w,h);grd.addColorStop(0,'#fff8d9');grd.addColorStop(1,'#e8f3ff');ctx.fillStyle=grd;ctx.fillRect(0,0,w,h);ctx.strokeStyle='#d8e1ee';for(let x=40;x<w;x+=80){ctx.beginPath();ctx.moveTo(x,70);ctx.lineTo(x,h);ctx.stroke()} [['MÓVEA QUARTOS',30,24,'#08264a'],['PROMOÇÃO DE ROPEIROS',690,26,'#ffd21f'],['saída? talvez',760,585,'#e63946']].forEach((s)=>{ctx.fillStyle=s[3];ctx.fillRect(s[1],s[2],230,38);ctx.fillStyle=s[3]==='#08264a'?'#ffd21f':'#08264a';ctx.font='bold 18px system-ui';ctx.fillText(s[0],s[1]+14,s[2]+25)}); for(let i=0;i<7;i++){ctx.fillStyle=i%2?'#fff':'#dce9ff';round(ctx,80+i*130,170+(i%3)*120,95,58,12,true);ctx.fillStyle='#08264a';ctx.fillRect(90+i*130,185+(i%3)*120,75,8)}}
function drawLuis(ctx,p,photo){ctx.save();ctx.translate(p.x,p.y);ctx.shadowColor='#0004';ctx.shadowBlur=12;ctx.fillStyle='#12345a';round(ctx,-18,12,36,28,10,true);ctx.fillStyle='#ffd21f';round(ctx,-24,-18,48,42,14,true);ctx.fillStyle='#f6c58f';ctx.beginPath();ctx.arc(0,-36,24,0,7);ctx.fill();ctx.fillStyle='#2b211f';ctx.beginPath();ctx.arc(-4,-49,24,3.2,6.2);ctx.fill();ctx.fillRect(-18,-36,36,10);ctx.fillStyle='#2b211f';ctx.fillRect(-14,-40,9,4);ctx.fillRect(6,-40,9,4);ctx.fillStyle='#fff';ctx.fillRect(-10,-28,20,5);ctx.fillStyle='#fff';round(ctx,10,-5,22,14,4,true);ctx.fillStyle='#e63946';ctx.font='8px system-ui';ctx.fillText('Luís',14,4); if(photo){ctx.save();ctx.beginPath();ctx.arc(0,-42,34,0,7);ctx.clip(); if(luisPhoto.complete&&luisPhoto.naturalWidth)ctx.drawImage(luisPhoto,-34,-76,68,68); ctx.restore();ctx.strokeStyle='#ffd21f';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,-42,36,0,7);ctx.stroke()}ctx.restore()}
function drawItem(ctx,it){ctx.save();ctx.translate(it.x,it.y);ctx.fillStyle={pillow:'#fff',bed:'#75a7ff',tag:'#ffd21f',wardrobe:'#8b5e34',power:'#e63946'}[it.type];round(ctx,-20,-16,40,32,10,true);ctx.fillStyle='#08264a';ctx.font='20px system-ui';ctx.fillText({pillow:'☁️',bed:'🛏️',tag:'🏷️',wardrobe:'▥',power:'⚡'}[it.type],-11,8);ctx.restore()}
function drawCustomer(ctx,c){ctx.fillStyle=c.happy?'#2ec27e':c.patience<30?'#e63946':'#7c5cff';ctx.beginPath();ctx.arc(c.x,c.y,18,0,7);ctx.fill();round(ctx,c.x-72,c.y-58,144,34,10,true);ctx.fillStyle='#08264a';ctx.font='11px system-ui';ctx.fillText(c.ask.slice(0,25),c.x-64,c.y-37);ctx.fillStyle='#ffd21f';ctx.fillRect(c.x-25,c.y+24,50*(c.patience/100),5)}
function drawMini(ctx,m){ctx.fillStyle='#08264add';round(ctx,300,235,400,150,22,true);ctx.fillStyle='#fff';ctx.font='bold 24px system-ui';ctx.fillText('MONTAR CAMA!',405,275);ctx.font='18px system-ui';ctx.fillText(`Espaço ${m.hit}/${m.need} · ${m.t.toFixed(1)}s`,400,320)}
function drawMenu(ctx,w,h,s){ctx.fillStyle='#0008';ctx.fillRect(0,0,w,h);drawLuis(ctx,{x:500,y:205},false)} function round(ctx,x,y,w,h,r,fill){ctx.beginPath();ctx.roundRect(x,y,w,h,r);fill?ctx.fill():ctx.stroke()}
ReactDOM.createRoot(document.getElementById('root')).render(<App/>);
